// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMlqqDmw1ij_mhWCwYlVG3f512tqtGC4c',
    appId: '1:518255327198:web:de59b13ee2938efbd48f4f',
    messagingSenderId: '518255327198',
    projectId: 'social-ap-af02d',
    authDomain: 'social-ap-af02d.firebaseapp.com',
    storageBucket: 'social-ap-af02d.appspot.com',
    measurementId: 'G-ZN01QT1FXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0nd3pcI4GD6fEJyg3jM7sxSRucOmI2uE',
    appId: '1:518255327198:android:3ba1ade6c053e4cdd48f4f',
    messagingSenderId: '518255327198',
    projectId: 'social-ap-af02d',
    storageBucket: 'social-ap-af02d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb-2OMwyV8JW0c2Fyxqr1-PkPNSrBDyk0',
    appId: '1:518255327198:ios:6e51ede582cdf4d7d48f4f',
    messagingSenderId: '518255327198',
    projectId: 'social-ap-af02d',
    storageBucket: 'social-ap-af02d.appspot.com',
    iosBundleId: 'com.example.socialAp',
  );
}
